POST http://127.0.0.1:8000/patients/
Content-Type: application/json

{
    "firstName": "Ali",
    "lastName": "Ben",
    "email": "ali@mail.com",
    "phoneNumber": "0600000000",
    "address": "Casablanca"
}

###
GET http://127.0.0.1:8000/patients/
###
POST http://127.0.0.1:8000/profiles/
Content-Type: application/json

{
  "person": "a7f88797-5da6-4532-8bba-569aed4fe100",
  "photo" : "/media/profiles/img2.jpeg",
  "biography": "Patient intéressé par suivi nutritionnel"
}