POST http://127.0.0.1:8000/patients/
Content-Type: application/json

{
    "firstName": "Salim",
    "lastName": "AGG",
    "email": "salim@mail.com",
    "phoneNumber": "0600000000",
    "address": "Paris"
}

###
GET http://127.0.0.1:8000/patients/
###
POST http://127.0.0.1:8000/profiles/
Content-Type: application/json

{
  "person": "8d4cae63-ecb4-4b74-be34-8a3717fbcc00",
  "photo": "img1.jpeg/",
  "biography": "Patient intéressé par suivi nutritionnel"
}


###
GET  http://127.0.0.1:8000/profiles/