# Generated by Django 5.2.11 on 2026-02-24 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lastName", models.CharField(max_length=150)),
                ("firstName", models.CharField(max_length=150)),
                ("phoneNumber", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("createAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-createAt"],
            },
        ),
    ]
