# Generated by Django 5.2.11 on 2026-02-26 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lastName", models.CharField(max_length=150)),
                ("firstName", models.CharField(max_length=150)),
                ("phoneNumber", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=254)),
                ("createAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-createAt"],
            },
        ),
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.person",
                    ),
                ),
                ("expertise", models.CharField(max_length=150)),
            ],
            bases=("app.person",),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.person",
                    ),
                ),
            ],
            bases=("app.person",),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="profiles/photos")),
                ("biography", models.TextField()),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="app.person",
                    ),
                ),
            ],
        ),
    ]
